enum ItemTypeEnum {
  HOMEPAGE_SLIDE_PLAYLIST("HOMEPAGE_SLIDE_PLAYLIST"),
  HOMEPAGE_SLIDE_LISTEN_LIVE("HOMEPAGE_SLIDE_LISTEN_LIVE"),
  HOMEPAGE_SLIDE_SONGLIST_ALIGN("HOMEPAGE_SLIDE_SONGLIST_ALIGN"),
  HOMEPAGE_NEW_SONG_NEW_ALBUM("HOMEPAGE_NEW_SONG_NEW_ALBUM"),
  SHUFFLE_MUSIC_CALENDAR("SHUFFLE_MUSIC_CALENDAR");

  final String value;

  const ItemTypeEnum(this.value);
}


enum AlbumTypeEnum {
  NEW_SONG_HOMEPAGE("NEW_SONG_HOMEPAGE"),
  NEW_ALBUM_HOMEPAGE("NEW_ALBUM_HOMEPAGE"),
  DIGITAL_ALBUM_HOMEPAGE("DIGITAL_ALBUM_HOMEPAGE");

  final String value;

  const AlbumTypeEnum(this.value);
}